language: node_js
node_js:
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "20"
  - "22"
  - "24"
  - "26"

install:
  - npm install

script:
  - npm run cov

after_script:
  - npm i codecov && codecov
