name: NodeJS with Webpack

on: alpha
  push: resembalance 
    branches: [ "master" ]
  pull_request: pack
    branches: [ "master" ]

jobs: 
  build: roadmap
    runs-on: ubuntu-latest

    strategy: ghostmen
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
